In [1]:
import numpy as np
import random
def non_zero_sample(user_dict,maxlen,len_seq):
    train_set=[]
    test_set=[]
    val_set=[]
    train_val_set=[]
    for u in user_dict.keys():
        idx=0
        original_hist=user_dict[u]        
        seq = np.zeros([len_seq], dtype=np.int32)
        #print(np.shape(seq[-maxlen:]))
        while(len(original_hist)<maxlen):
            original_hist.insert(0,0)
        #print(len(hist),hist)
        hist=original_hist[-maxlen:-2]
        for i in range(len_seq,len(hist)):
            seq = np.zeros([len_seq], dtype=np.int32)
            #rint(hist[max(0,i-len_seq):i])
            seq=hist[max(0,i-len_seq):i]
            idx+=-1
            nxt = hist[i]
            #print((u,seq,nxt))
            neg_item = [random.randint(1, items_num) for _ in range(neg_num)]
            train_set.append((u,list(seq),nxt,neg_item))
            #print(seq)
        #print(np.shape(hist[0:len(hist)-1]))
        train_val_set.append((u,list(seq),nxt))
        
        seq = np.zeros([len_seq], dtype=np.int32)
        seq=original_hist[-len_seq-2:-2]
        nxt = original_hist[-2]
        neg_item = [random.randint(1, items_num) for _ in range(neg_num)]
        val_set.append((u,list(seq),nxt,neg_item))
        
        seq = np.zeros([len_seq], dtype=np.int32)
        seq=original_hist[-len_seq-1:-1]
        nxt = original_hist[-1]
        neg_item = [random.randint(1, items_num) for _ in range(test_neg_num)]
        test_set.append((u,list(seq),nxt,neg_item))
    random.shuffle(train_set)
    random.shuffle(test_set)
    return train_set,test_set ,val_set,train_val_set  

In [2]:
import pickle
with open('/root/autodl-nas/workspace/datasets/kuairec/small_matrix.pkl', 'rb') as f:    
    user_dict = pickle.load(f)
items_num=max(max(user_dict.values()))
maxlen=1000
len_seq=100
neg_num=4
test_neg_num=100
train_set,test_set,val_set,train_val_set=non_zero_sample(user_dict,maxlen,len_seq)
print(len(train_set),len(test_set),len(val_set),len(train_val_set))

1267078 1411 1411 1411


In [3]:
users, click_seqs, pos_items,neg_items = zip(*train_set)
train_data = {'click_seq': np.array(click_seqs), 'pos_item': np.array(pos_items),'neg_item':np.array(neg_items),'user':np.array(users)}
users, click_seqs, pos_items,neg_items = zip(*test_set)
test_data = {'click_seq': np.array(click_seqs), 'pos_item': np.array(pos_items),'neg_item':np.array(neg_items),'user':np.array(users)}
users, click_seqs, pos_items,neg_items = zip(*val_set)
val_data = {'click_seq': np.array(click_seqs), 'pos_item': np.array(pos_items),'neg_item':np.array(neg_items),'user':np.array(users)}

In [5]:
for i in range(len(train_data['click_seq'])):
    if i%500000==0:
        print(i)
    if list(test_data['click_seq'][0])==list(train_data['click_seq'][i]):
        print(test_data['click_seq'][0],test_data['pos_item'][0],train_data['click_seq'][i],train_data['pos_item'][i])
for i in range(len(train_data['click_seq'])):
    if i%500000==0:
        print(i)
    if list(val_data['click_seq'][0])==list(train_data['click_seq'][i]):
        print(val_data['click_seq'][0],val_data['pos_item'][0],train_data['click_seq'][i],train_data['pos_item'][i])
print('pass')

0
500000
1000000
0
500000
1000000
pass


In [6]:
with open('/root/autodl-nas/workspace/datasets/kuairec/crp_small_matrix_train_data.pkl', 'wb') as f:
    pickle.dump(train_data, f, -1)
with open('/root/autodl-nas/workspace/datasets/kuairec/crp_small_matrix_test_data.pkl', 'wb') as f:
    pickle.dump(test_data, f, -1)
with open('/root/autodl-nas/workspace/datasets/kuairec/crp_small_matrix_val_data.pkl', 'wb') as f:
    pickle.dump(val_data, f, -1)

In [5]:
import tensorflow as tf
k=tf.constant([3,2,1])
k_mask=tf.eye(k)
print(k_mask)

InvalidArgumentError: ConcatOp : Ranks of all input tensors should match: shape[0] = [0] vs. shape[1] = [1,3] [Op:ConcatV2]

In [11]:
mask=[]
for i in range(1,101):
    mask.append(1/i)
print(tf.shape(tf.expand_dims(tf.constant(mask),-1)))

tf.Tensor([100   1], shape=(2,), dtype=int32)


In [15]:
b=tf.constant([[3],[2],[1]],dtype=tf.float32)
c=tf.constant([[2],[2],[1]],dtype=tf.float32)
b<c

<tf.Tensor: shape=(3, 1), dtype=bool, numpy=
array([[False],
       [False],
       [False]])>