In [8]:
import numpy as np

def Draw_CRP_Direct_Sample(N = 10, alpha = 1, T = 50, VERBOSE = False):

    Z_table = np.zeros((T,N))
    
    for t in range(T):
    
        Z = np.zeros(N,dtype=int)

        for i in range(N):

            if i == 0:
                Z[i] = 1
            else:
                if VERBOSE:
                    print(Z)
                unique, counts = np.unique(Z, return_counts=True)

                # remove the zeros unsigned tables
                if unique[0] == 0:
                    unique = np.delete(unique,0)
                    counts = np.delete(counts,0)

                #if VERBOSE:
                #    print "unique,counts,alpha", unique,counts,alpha

                # added alpha to the end of the counts (weights) array
                counts = np.append(counts,alpha)

                # also the new table index will be the max of table seen so far
                unique = np.append(unique,max(unique)+1)

                #print "np.append(counts,alpha)",counts

                #if VERBOSE:
                #    print sum(counts)
                u = np.random.uniform()*sum(counts)

                a_counts = np.cumsum(counts)

                if VERBOSE:
                    print(counts, u, a_counts > u)

                # first index where accumuated sum is greater than random variable
                index =  np.argmax(a_counts > u)

                #print "index", index

                Z[i] = unique[index]

            if VERBOSE:
                print(Z)
                print("\n\n") 
        
        
        Z_table[t,:] = Z
    return Z_table

In [12]:
alpha = 3
N = 10
T = 10000
VERBOSE = False
burn_in = int(T/10)

Z_table = Draw_CRP_Direct_Sample(N, alpha , T , VERBOSE)
table_numbers = np.zeros(T,dtype=int)

for t in range(T):
    unique, count = np.unique(Z_table[t,:], return_counts=True)
    table_numbers[t] = len(count)
exp_average = np.mean(table_numbers)    
print("sample E(K) = ", exp_average)
print("\n")

sample E(K) =  4.7836




ModuleNotFoundError: No module named 'scipy'

In [21]:
import tensorflow as tf
alpha = 3
N = 10
print(alpha * (tf.math.digamma(tf.cast((alpha + N),tf.float32))-tf.math.digamma(tf.cast((alpha),tf.float32))))

from scipy.special import digamma, gamma, gammaln
theory_average = alpha * (digamma(alpha + N) - digamma(alpha))
print(theory_average)

tf.Tensor(4.8096323, shape=(), dtype=float32)
4.809632034632035


In [22]:
tf.math.ceil(alpha * (tf.math.digamma(tf.cast((alpha + N),tf.float32))-tf.math.digamma(tf.cast((alpha),tf.float32))))

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

<tf.Tensor: shape=(), dtype=float32, numpy=0.92278427>

<tf.Tensor: shape=(), dtype=float32, numpy=4.8096323>

In [15]:
digamma(alpha + N)-digamma(alpha)

1.603210678210678